### PR TITLE
Fix bad merge (#14), remove process.env call

### PR DESCRIPTION
**Pull request by Firescar96**

### CODE REVIEW

**Comment by Firescar96** [comment]
hold on, I forgot to remove an old file

**Comment by whitj00** [comment]
https://github.com/etherparty/explorer/pull/15/files#diff-2de9eda1655d499e934e7465e87ca0bdL30 should stay the same with process env call

**Comment by Firescar96** [comment]
I followed the Readme instructions, but that code doesn't seem to work, at least not in the browser.

**Comment by Firescar96** [comment]
@whitj00 does process.env work in your browser?

**Comment by whitj00** [comment]
It's not supposed to run in the browser, app.js runs server side

**Comment by Firescar96** [comment]
screenshot-20160802-00 17 53

Are you sure? Have you tried running the instructions from the readme to run the code?

**Comment by whitj00** [comment]
Sorry, you're correct

**Pull request merged**
